# ==============================================================================
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# ==============================================================================
version: "3"
networks: 
  ovms-bridge:
    driver: bridge
services: 
  ovms-server:
    image: jkalapati/ovms-server
    hostname: ovms-server
    ports: 
      - "9000:9000"
      - "9001:9001"
    expose: 
      - "9000"
    networks: 
      - ovms-bridge
    command: [--port=9000, --model_name=face-detection, --model_path=/models, --shape=auto]
    tty: 
      true
      
  ovms-client: 
    image: jkalapati/ovms-client
    environment: 
      SERVER_NAME: ovms-server
      GRPC_PORT: 9000
    ports:
      - "8000:8000"
    networks: 
      - ovms-bridge
    depends_on:
      - ovms-server
    links: 
      - ovms-server
    tty:
      true
